---
blocks:
- minecraft:acacia_hanging_sign
- minecraft:allow
- minecraft:azalea
- minecraft:bamboo_block
- minecraft:bamboo_button
- minecraft:bamboo_door
- minecraft:bamboo_double_slab
- minecraft:bamboo_fence
- minecraft:bamboo_fence_gate
- minecraft:bamboo_hanging_sign
- minecraft:bamboo_mosaic
- minecraft:bamboo_mosaic_double_slab
- minecraft:bamboo_mosaic_slab
- minecraft:bamboo_mosaic_stairs
- minecraft:bamboo_planks
- minecraft:bamboo_pressure_plate
- minecraft:bamboo_slab
- minecraft:bamboo_stairs
- minecraft:bamboo_standing_sign
- minecraft:bamboo_trapdoor
- minecraft:bamboo_wall_sign
- minecraft:bee_nest
- minecraft:beehive
- minecraft:birch_hanging_sign
- minecraft:border_block
- minecraft:bubble_column
- minecraft:calibrated_sculk_sensor
- minecraft:camera
- minecraft:campfire
- minecraft:chain_command_block
- minecraft:cherry_hanging_sign
- minecraft:cherry_sapling
- minecraft:chiseled_copper
- minecraft:chiseled_tuff
- minecraft:chiseled_tuff_bricks
- minecraft:command_block
- minecraft:composter
- minecraft:conduit
- minecraft:copper_bulb
- minecraft:copper_door
- minecraft:copper_grate
- minecraft:copper_trapdoor
- minecraft:crafter
- minecraft:crimson_fungus
- minecraft:crimson_hanging_sign
- minecraft:crimson_nylium
- minecraft:dark_oak_hanging_sign
- minecraft:decorated_pot
- minecraft:deny
- minecraft:dispenser
- minecraft:dripstone_block
- minecraft:dropper
- minecraft:end_gateway
- minecraft:end_portal
- minecraft:exposed_chiseled_copper
- minecraft:exposed_copper_bulb
- minecraft:exposed_copper_door
- minecraft:exposed_copper_grate
- minecraft:exposed_copper_trapdoor
- minecraft:flowering_azalea
- minecraft:frog_spawn
- minecraft:grindstone
- minecraft:honey_block
- minecraft:infested_deepslate
- minecraft:jigsaw
- minecraft:jungle_hanging_sign
- minecraft:kelp
- minecraft:lodestone
- minecraft:mangrove_hanging_sign
- minecraft:mangrove_propagule
- minecraft:moss_block
- minecraft:moss_carpet
- minecraft:moving_block
- minecraft:nether_sprouts
- minecraft:oak_hanging_sign
- minecraft:observer
- minecraft:oxidized_chiseled_copper
- minecraft:oxidized_copper_bulb
- minecraft:oxidized_copper_door
- minecraft:oxidized_copper_grate
- minecraft:oxidized_copper_trapdoor
- minecraft:piston
- minecraft:piston_arm_collision
- minecraft:pointed_dripstone
- minecraft:polished_tuff
- minecraft:polished_tuff_double_slab
- minecraft:polished_tuff_slab
- minecraft:polished_tuff_stairs
- minecraft:polished_tuff_wall
- minecraft:powder_snow
- minecraft:repeating_command_block
- minecraft:respawn_anchor
- minecraft:scaffolding
- minecraft:sculk_catalyst
- minecraft:sculk_sensor
- minecraft:sculk_shrieker
- minecraft:sculk_vein
- minecraft:seagrass
- minecraft:sniffer_egg
- minecraft:soul_campfire
- minecraft:spruce_hanging_sign
- minecraft:sticky_piston
- minecraft:sticky_piston_arm_collision
- minecraft:stripped_bamboo_block
- minecraft:structure_block
- minecraft:structure_void
- minecraft:suspicious_gravel
- minecraft:suspicious_sand
- minecraft:target
- minecraft:trial_spawner
- minecraft:tuff_brick_double_slab
- minecraft:tuff_brick_slab
- minecraft:tuff_brick_stairs
- minecraft:tuff_brick_wall
- minecraft:tuff_bricks
- minecraft:tuff_double_slab
- minecraft:tuff_slab
- minecraft:tuff_stairs
- minecraft:tuff_wall
- minecraft:turtle_egg
- minecraft:unknown
- minecraft:vault
- minecraft:warped_fungus
- minecraft:warped_hanging_sign
- minecraft:warped_nylium
- minecraft:waxed_chiseled_copper
- minecraft:waxed_copper_bulb
- minecraft:waxed_copper_door
- minecraft:waxed_copper_grate
- minecraft:waxed_copper_trapdoor
- minecraft:waxed_exposed_chiseled_copper
- minecraft:waxed_exposed_copper_bulb
- minecraft:waxed_exposed_copper_door
- minecraft:waxed_exposed_copper_grate
- minecraft:waxed_exposed_copper_trapdoor
- minecraft:waxed_oxidized_chiseled_copper
- minecraft:waxed_oxidized_copper_bulb
- minecraft:waxed_oxidized_copper_door
- minecraft:waxed_oxidized_copper_grate
- minecraft:waxed_oxidized_copper_trapdoor
- minecraft:waxed_weathered_chiseled_copper
- minecraft:waxed_weathered_copper_bulb
- minecraft:waxed_weathered_copper_door
- minecraft:waxed_weathered_copper_grate
- minecraft:waxed_weathered_copper_trapdoor
- minecraft:weathered_chiseled_copper
- minecraft:weathered_copper_bulb
- minecraft:weathered_copper_door
- minecraft:weathered_copper_grate
- minecraft:weathered_copper_trapdoor
items:
- minecraft:acacia_chest_boat
- minecraft:acacia_hanging_sign
- minecraft:agent_spawn_egg
- minecraft:allay_spawn_egg
- minecraft:angler_pottery_sherd
- minecraft:archer_pottery_sherd
- minecraft:armadillo_scute
- minecraft:armadillo_spawn_egg
- minecraft:armor_stand
- minecraft:arms_up_pottery_sherd
- minecraft:axolotl_bucket
- minecraft:axolotl_spawn_egg
- minecraft:balloon
- minecraft:bamboo_chest_raft
- minecraft:bamboo_door
- minecraft:bamboo_hanging_sign
- minecraft:bamboo_raft
- minecraft:bamboo_sign
- minecraft:bat_spawn_egg
- minecraft:bee_spawn_egg
- minecraft:birch_chest_boat
- minecraft:birch_hanging_sign
- minecraft:blade_pottery_sherd
- minecraft:blaze_spawn_egg
- minecraft:bogged_spawn_egg
- minecraft:bordure_indented_banner_pattern
- minecraft:breeze_spawn_egg
- minecraft:brewer_pottery_sherd
- minecraft:brush
- minecraft:burn_pottery_sherd
- minecraft:camel_spawn_egg
- minecraft:camera
- minecraft:campfire
- minecraft:carrot_on_a_stick
- minecraft:cat_spawn_egg
- minecraft:cave_spider_spawn_egg
- minecraft:cherry_boat
- minecraft:cherry_chest_boat
- minecraft:cherry_hanging_sign
- minecraft:chest_minecart
- minecraft:chicken_spawn_egg
- minecraft:cod_bucket
- minecraft:cod_spawn_egg
- minecraft:command_block_minecart
- minecraft:copper_door
- minecraft:cow_spawn_egg
- minecraft:creeper_banner_pattern
- minecraft:creeper_spawn_egg
- minecraft:crimson_hanging_sign
- minecraft:crossbow
- minecraft:danger_pottery_sherd
- minecraft:dark_oak_chest_boat
- minecraft:dark_oak_hanging_sign
- minecraft:diamond_horse_armor
- minecraft:dolphin_spawn_egg
- minecraft:donkey_spawn_egg
- minecraft:drowned_spawn_egg
- minecraft:elder_guardian_spawn_egg
- minecraft:elytra
- minecraft:empty_map
- minecraft:end_crystal
- minecraft:ender_dragon_spawn_egg
- minecraft:ender_eye
- minecraft:enderman_spawn_egg
- minecraft:endermite_spawn_egg
- minecraft:evoker_spawn_egg
- minecraft:explorer_pottery_sherd
- minecraft:exposed_copper_door
- minecraft:field_masoned_banner_pattern
- minecraft:filled_map
- minecraft:firework_rocket
- minecraft:firework_star
- minecraft:flower_banner_pattern
- minecraft:fox_spawn_egg
- minecraft:friend_pottery_sherd
- minecraft:frog_spawn_egg
- minecraft:ghast_spawn_egg
- minecraft:globe_banner_pattern
- minecraft:glow_squid_spawn_egg
- minecraft:glow_stick
- minecraft:goat_horn
- minecraft:goat_spawn_egg
- minecraft:golden_horse_armor
- minecraft:guardian_spawn_egg
- minecraft:heart_pottery_sherd
- minecraft:heartbreak_pottery_sherd
- minecraft:hoglin_spawn_egg
- minecraft:hopper_minecart
- minecraft:horse_spawn_egg
- minecraft:howl_pottery_sherd
- minecraft:husk_spawn_egg
- minecraft:ice_bomb
- minecraft:iron_golem_spawn_egg
- minecraft:iron_horse_armor
- minecraft:jungle_chest_boat
- minecraft:jungle_hanging_sign
- minecraft:kelp
- minecraft:lead
- minecraft:leather_horse_armor
- minecraft:lingering_potion
- minecraft:llama_spawn_egg
- minecraft:lodestone_compass
- minecraft:magma_cube_spawn_egg
- minecraft:mangrove_chest_boat
- minecraft:mangrove_hanging_sign
- minecraft:miner_pottery_sherd
- minecraft:mojang_banner_pattern
- minecraft:mooshroom_spawn_egg
- minecraft:mourner_pottery_sherd
- minecraft:mule_spawn_egg
- minecraft:music_disc_relic
- minecraft:nether_sprouts
- minecraft:npc_spawn_egg
- minecraft:oak_chest_boat
- minecraft:oak_hanging_sign
- minecraft:ocelot_spawn_egg
- minecraft:oxidized_copper_door
- minecraft:panda_spawn_egg
- minecraft:parrot_spawn_egg
- minecraft:phantom_spawn_egg
- minecraft:pig_spawn_egg
- minecraft:piglin_banner_pattern
- minecraft:piglin_brute_spawn_egg
- minecraft:piglin_spawn_egg
- minecraft:pillager_spawn_egg
- minecraft:plenty_pottery_sherd
- minecraft:polar_bear_spawn_egg
- minecraft:powder_snow_bucket
- minecraft:prize_pottery_sherd
- minecraft:pufferfish_bucket
- minecraft:pufferfish_spawn_egg
- minecraft:rabbit_spawn_egg
- minecraft:rapid_fertilizer
- minecraft:ravager_spawn_egg
- minecraft:recovery_compass
- minecraft:saddle
- minecraft:salmon_bucket
- minecraft:salmon_spawn_egg
- minecraft:sheaf_pottery_sherd
- minecraft:sheep_spawn_egg
- minecraft:shelter_pottery_sherd
- minecraft:shield
- minecraft:shulker_spawn_egg
- minecraft:silverfish_spawn_egg
- minecraft:skeleton_horse_spawn_egg
- minecraft:skeleton_spawn_egg
- minecraft:skull_banner_pattern
- minecraft:skull_pottery_sherd
- minecraft:slime_spawn_egg
- minecraft:sniffer_spawn_egg
- minecraft:snort_pottery_sherd
- minecraft:snow_golem_spawn_egg
- minecraft:soul_campfire
- minecraft:sparkler
- minecraft:spider_spawn_egg
- minecraft:spruce_chest_boat
- minecraft:spruce_hanging_sign
- minecraft:stray_spawn_egg
- minecraft:strider_spawn_egg
- minecraft:tadpole_bucket
- minecraft:tadpole_spawn_egg
- minecraft:tnt_minecart
- minecraft:trader_llama_spawn_egg
- minecraft:trial_key
- minecraft:trident
- minecraft:tropical_fish_bucket
- minecraft:tropical_fish_spawn_egg
- minecraft:turtle_spawn_egg
- minecraft:vex_spawn_egg
- minecraft:vindicator_spawn_egg
- minecraft:wandering_trader_spawn_egg
- minecraft:warden_spawn_egg
- minecraft:warped_fungus_on_a_stick
- minecraft:warped_hanging_sign
- minecraft:waxed_copper_door
- minecraft:waxed_exposed_copper_door
- minecraft:waxed_oxidized_copper_door
- minecraft:waxed_weathered_copper_door
- minecraft:weathered_copper_door
- minecraft:wind_charge
- minecraft:witch_spawn_egg
- minecraft:wither_skeleton_spawn_egg
- minecraft:wither_spawn_egg
- minecraft:wolf_armor
- minecraft:wolf_spawn_egg
- minecraft:zoglin_spawn_egg
- minecraft:zombie_horse_spawn_egg
- minecraft:zombie_pigman_spawn_egg
- minecraft:zombie_villager_spawn_egg
...
